### ISSUE TITLE
Добавить скриншоты с iOS

### ISSUE THREAD

**Issue by hugonote** [MrAlonas/nng.alonas.ml#4]
Добавить в FAQ скриншоты с iOS

**Comment by MrAlonas** [comment]
Попытки в январе были, но чёт не вышло. Либо юзер совсем деревянный и не понимает что от него требуется, либо просто в моём окружении и окружении друзей не было тех, у кого есть тот самый телефон на базе iOS. Но попробуем.

**Comment by MrAlonas** [comment]
Готово https://github.com/MrAlonas/nng.alonas.ml/commit/d842235eceabedea2e1a093061f17794cda1df8d
